"""One SQLAlchemy Enum object per Postgres enum type, reused across tables."""

from .. import enums as e
from .base import pg_enum

user_role = pg_enum(e.UserRole, "user_role")
onboarding_path = pg_enum(e.OnboardingPath, "onboarding_path")
literacy_level = pg_enum(e.LiteracyLevel, "literacy_level")
education_level = pg_enum(e.EducationLevel, "education_level")
skill_type = pg_enum(e.SkillType, "skill_type")
taxonomy_status = pg_enum(e.TaxonomyStatus, "taxonomy_status")
skill_relation_type = pg_enum(e.SkillRelationType, "skill_relation_type")
suggestion_status = pg_enum(e.SuggestionStatus, "suggestion_status")
skill_source = pg_enum(e.SkillSource, "skill_source")
requirement_level = pg_enum(e.RequirementLevel, "requirement_level")
company_size = pg_enum(e.CompanySize, "company_size")
contract_type = pg_enum(e.ContractType, "contract_type")
work_mode = pg_enum(e.WorkMode, "work_mode")
offer_status = pg_enum(e.OfferStatus, "offer_status")
offer_source = pg_enum(e.OfferSource, "offer_source")
application_status = pg_enum(e.ApplicationStatus, "application_status")
hiring_decision = pg_enum(e.HiringDecision, "hiring_decision")
gap_type = pg_enum(e.GapType, "gap_type")
roadmap_status = pg_enum(e.RoadmapStatus, "roadmap_status")
roadmap_item_status = pg_enum(e.RoadmapItemStatus, "roadmap_item_status")
course_modality = pg_enum(e.CourseModality, "course_modality")
verification_status = pg_enum(e.VerificationStatus, "verification_status")
market_data_origin = pg_enum(e.MarketDataOrigin, "market_data_origin")
market_indicator_type = pg_enum(e.MarketIndicatorType, "market_indicator_type")
conversation_channel = pg_enum(e.ConversationChannel, "conversation_channel")
document_type = pg_enum(e.DocumentType, "document_type")
processing_status = pg_enum(e.ProcessingStatus, "processing_status")
ingestion_source = pg_enum(e.IngestionSource, "ingestion_source")
embedding_entity = pg_enum(e.EmbeddingEntity, "embedding_entity")
