const formatArabe = (valeur) => new Intl.NumberFormat('ar-TN', { useGrouping: false }).format(valeur)

const textes = {
  marque: 'مهارة',
  espaceCandidat: 'فضاء المترشّح',
  parcours: 'مسار التسجيل',
  nombreQuestions: 'تسجيل بالصوت · ٤ أسئلة',
  accueilTitre: 'خلّينا نحكيو على خدمتك الجاية.',
  accueilDescription: 'جاوبنا بالصوت على شوية أسئلة، وفي الآخر نحضّرولك عرض خدمة.',
  commencer: 'ابدا',
  preparation: 'نحضّرو...',
  confidentialite: 'إجاباتك نستعملوها كان باش نحضّرولك عرض الخدمة.',
  aTonRythme: 'كمّل على راحتك',
  aBientot: 'نستناو فيك',
  questionProgression: (courante, total) => `السؤال ${formatArabe(courante)} من ${formatArabe(total)}`,
  questionNumero: (numero) => `السؤال ${formatArabe(numero)}`,
  questionInconnue: 'ما لقيناش السؤال هذا.',
  questions: {
    metier: 'شنوّة الخدمة اللي تخدم فيها؟',
    date: 'من وقتاش تنجم تبدا تخدم؟',
    gouvernorat: 'في أنهي ولاية تسكن؟',
    telephone: 'شنوّة رقم تلفونك؟',
  },
  reecouter: 'عاود اسمع السؤال',
  reponseEnregistree: 'تسجّلت إجابتك',
  transcription: 'استنّى شوية، نكتبو في الجواب...',
  ceQuiEstCompris: 'هذا اللي فهمتو',
  valeurRetenue: 'الإجابة اللي تسجّلت',
  nonPrecise: 'ما تحددش',
  enregistrer: 'سجّل',
  arreter: 'وقّف',
  reessayer: 'عاود',
  envoyerFichierAudio: 'ابعث ملف صوتي',
  choisirFichierAudio: 'اختار ملف صوتي',
  enregistrementEnCours: 'قاعدين نسجّلوا...',
  suivant: 'التالي',
  voirOffre: 'نشوف عرض الخدمة',
  parcoursTermine: 'كمّلنا التسجيل',
  offrePrete: 'عرض الخدمة متاعك حاضر.',
  proposition: 'عرض الخدمة',
  preparationOffre: 'قاعدين نحضّروا عرض الخدمة...',
  recapAudio: 'ملخّص بالصوت',
  valider: 'نوافق',
  refuser: 'نرفض',
  offreValidee: 'وافقت على عرض الخدمة.',
  offreRefusee: 'رفضت عرض الخدمة.',
  pourLaDemo: 'في النسخة التجريبية.',
  recommencer: 'ابدا من جديد',
  creationSession: 'قاعدين نعملوا تسجيل جديد...',
  audioIndisponible: 'المتصفّح متاعك ما يدعمش تشغيل الصوت.',
  audioBloque: 'المتصفّح ما بداش يشغّل الصوت وحدو. اضغط على «عاود اسمع السؤال» باش تسمعو.',
  erreurLectureAudio: 'ما نجّمش نشغّلوا الصوت. تثبّت من صوت جهازك.',
  reponseNonExtraite: 'ما تحددتش الإجابة',
  telephoneDansOffre: 'رقم التلفون:',
  erreurs: {
    api: 'الخدمة موش متاحة توّة. تثبّت اللي الخادم يخدم وعاود.',
    microphoneRefuse: 'ما سمحتش للمتصفّح يستعمل الميكرو. فعّل الإذن ولا ابعث ملف صوتي.',
    microphoneAbsent: 'ما لقيناش ميكرو. ابعث ملف صوتي باش تكمّل.',
    microphoneErreur: 'ما نجّمش نوصلوا للميكرو. تثبّت منو ولا ابعث ملف صوتي.',
    microphoneIndisponible: 'التسجيل موش متاح في المتصفّح هذا. ابعث ملف صوتي.',
    enregistrement: 'صار مشكل في التسجيل. عاود ولا ابعث ملف صوتي.',
    enregistrementCourt: 'التسجيل قصير برشة. احكي ثانية على الأقل وعاود.',
    fichierVide: 'ملف الصوت فارغ. اختار ملف آخر وعاود.',
    fichierInvalide: 'ملف الصوت موش واضح. ابعث ملف صوتي صالح وعاود.',
    transcription_vide: 'ما سمعتش مليح، عاود من فضلك.',
    audio_vide: 'ما تسجّل حتى صوت. سجّل إجابتك وعاود.',
    audio_invalide: 'ملف الصوت موش واضح. ابعث ملف صوتي صالح وعاود.',
    transcription_echec: 'صار مشكل في كتابة الإجابة. عاود بعد شوية.',
    erreur400: 'الطلب موش صحيح. تثبّت من الإجابة وعاود.',
    erreur404: 'ما لقيناش التسجيل هذا.',
    erreur409: 'ما نجّمش نكمّلوا الطلب هذا توّة.',
    erreur413: 'ملف الصوت كبير برشة. اختار ملف أصغر من ٢٥ ميغا.',
    serveur: 'صار مشكل في الخادم. عاود بعد شوية.',
    autre: 'صار مشكل. عاود من فضلك.',
  },
}

export default textes